###
# SCSS Lint
###

.scss:stylelint:
  variables:
    TITLE: "stylelint"
    APP_PATH: "./app/stylelint"
    ADDITIONAL_COMMANDS: "npm install --no-save --audit=false"

scss:stylelint:image:build:
  extends:
    - .image:build
    - .scss:stylelint

scss:stylelint:slim:image:build:
  extends:
    - .slim:image:build
    - .scss:stylelint
  needs:
    - scss:stylelint:image:build

scss:stylelint:image:tag:
  extends:
    - .image:tag
    - .scss:stylelint
  needs:
    - scss:stylelint:slim:image:build
