###
# PHP Rector
###

.php:rector:
  variables:
    TITLE: "rector"
    APP_PATH: "./app/rector"

php:rector:image:build:
  extends:
    - .image:build
    - .php:rector

php:rector:slim:image:build:
  extends:
    - .slim:image:build
    - .php:rector
  needs:
    - php:rector:image:build
