###
# Composer Normalize
###
.composer:normalize:
  variables:
    TITLE: "composer-normalize"
    APP_PATH: "./app/composer-normalize"

composer:normalize:image:build:
  extends:
    - .image:build
    - .composer:normalize

composer:normalize:slim:image:build:
  extends:
    - .slim:image:build
    - .composer:normalize
  needs:
    - composer:normalize:image:build
