###
# ESlint
###
.js:eslint:
  variables:
    TITLE: "js-eslint"
    APP_PATH: "./app/eslint"
    ADDITIONAL_COMMANDS: "npm install --no-save --audit=false"

js:eslint:image:build:
  extends:
    - .image:build:npm
    - .js:eslint

js:eslint:slim:image:build:
  extends:
    - .slim:image:build
    - .js:eslint
  needs:
    - js:eslint:image:build

js:eslint:image:tag:
  extends:
    - .image:tag
    - .js:eslint
  needs:
    - js:eslint:slim:image:build
